sudo: required
services:
  - docker

before_install:
  - docker build -t shogotagami/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true shogotagami/react-app npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-927395323393"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
